CREATE TABLE IF NOT EXISTS produk (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nama TEXT NOT NULL,
    harga REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS keranjang (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produk_id INTEGER NOT NULL,
    jumlah INTEGER NOT NULL,
    FOREIGN KEY (produk_id) REFERENCES produk(id)
);
